### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [AlexeiFedya/adaptive-layout-mes-#2]
Thank you for the efforts! The slack chat looks like a good start.
Let's make it more or less close to original.
 - need to update fonts
 - add different types of messages
 - open some type of panels on the right area

More close to this
![image](https://user-images.githubusercontent.com/5592397/87516865-ba325700-c686-11ea-8498-de459b61f69c.png)

Also, I see [redundant margin/padding at the bottom](https://www.screencast.com/t/fKyA55oxaL). Could you check pelese why it happens and fix.

Everything cool in general, just need more attention to details.

**Comment by AlexeiFedya** [comment]
![2020-07-21_17-52-42](https://user-images.githubusercontent.com/57766198/88070400-4fe44f80-cb7b-11ea-8398-cd546a5f2148.png)
layout page - more close to this, pleas look new githubpages, and give me an answer

**Comment by AlexMokin** [comment]
1. Edit message box is out of place see image below
2. implement different types of message - ad least 3 (quote, file, image, vide etc.)

![image](https://user-images.githubusercontent.com/7272208/88205554-a4f49400-cc55-11ea-8665-3788aca3ffbe.png)

**Comment by AlexeiFedya** [comment]
ок, in my computer, i look this -
![2020-07-22_20-14-20](https://user-images.githubusercontent.com/57766198/88207240-2e0cca80-cc58-11ea-80fa-83f9d74b208e.png)
I will fix this, and add 3 types message

**Comment by AlexeiFedya** [comment]
ilya, pleas look my new gh pages  and look js-assigment repo, because I edited failed 10 days  ago, but you didn't see

**Comment by IlyaMokin** [comment]
Thanks, looks fine now. The issue can be closed. We will be  checking your js tasks soon, thanks for efforts and patience
